project:
  type: website
  # Zielordner für die gebaute Seite (relativ zum Projektordner):
  output-dir: ../InterMind.ch/analyse

website:
  title: "MAIHDA-Analyse"
  site-url: https://intermind.ch/analyse/
  # Kein Navbar für Einseiter:
  navbar: false
  page-navigation: true
  page-footer:
    left: "© 2025 InterMind – Lukas Batschelet"
    right: "Stand: {{< meta date >}}"
    border: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: show
    code-tools: true
    df-print: paged         # Tabellen hübsch
    fig-format: svg         # Plots als SVG (besser für Web)
    fig-width: 8
    fig-height: 5

execute:
  echo: true
  warning: false
  message: false

lang: de
editor: visual
